/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ScholarshipApprovalRelease } from './ScholarshipApprovalRelease.js';
export * as factories from './factories/index.js';
export { ScholarshipApprovalRelease__factory } from './factories/ScholarshipApprovalRelease__factory.js';