/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ScholarshipApprovalRelease {
      
    export type InstallmentStruct = {released: boolean, claimed: boolean, amount: BigNumberish, releasedAt: BigNumberish, claimDeadline: BigNumberish}

    export type InstallmentStructOutput = [released: boolean, claimed: boolean, amount: bigint, releasedAt: bigint, claimDeadline: bigint] & {released: boolean, claimed: boolean, amount: bigint, releasedAt: bigint, claimDeadline: bigint }
  

    export type ScholarshipStruct = {approved: boolean, totalAmount: BigNumberish, releasedAmount: BigNumberish, claimedAmount: BigNumberish, installments: BigNumberish, releasedInstallments: BigNumberish, claimedInstallments: BigNumberish, claimWindowSeconds: BigNumberish}

    export type ScholarshipStructOutput = [approved: boolean, totalAmount: bigint, releasedAmount: bigint, claimedAmount: bigint, installments: bigint, releasedInstallments: bigint, claimedInstallments: bigint, claimWindowSeconds: bigint] & {approved: boolean, totalAmount: bigint, releasedAmount: bigint, claimedAmount: bigint, installments: bigint, releasedInstallments: bigint, claimedInstallments: bigint, claimWindowSeconds: bigint }
  
    }

  export interface ScholarshipApprovalReleaseInterface extends Interface {
    getFunction(nameOrSignature: "approveScholarship" | "claimInstallment" | "fundScholarship" | "fundedBalance" | "getApprovedStudents" | "getInstallmentInfo" | "getScholarship" | "isApproved" | "owner" | "recoverExpiredInstallment" | "releaseInstallment"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ExpiredInstallmentRecovered" | "InstallmentClaimed" | "InstallmentReleased" | "ScholarshipApproved" | "ScholarshipFunded"): EventFragment;

    encodeFunctionData(functionFragment: 'approveScholarship', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimInstallment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundScholarship', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundedBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getApprovedStudents', values?: undefined): string;
encodeFunctionData(functionFragment: 'getInstallmentInfo', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getScholarship', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isApproved', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recoverExpiredInstallment', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'releaseInstallment', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'approveScholarship', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimInstallment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundScholarship', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundedBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApprovedStudents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInstallmentInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getScholarship', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recoverExpiredInstallment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseInstallment', data: BytesLike): Result;
  }

  
    export namespace ExpiredInstallmentRecoveredEvent {
      export type InputTuple = [student: AddressLike, installmentNumber: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [student: string, installmentNumber: bigint, amount: bigint];
      export interface OutputObject {student: string, installmentNumber: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InstallmentClaimedEvent {
      export type InputTuple = [student: AddressLike, installmentNumber: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [student: string, installmentNumber: bigint, amount: bigint];
      export interface OutputObject {student: string, installmentNumber: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InstallmentReleasedEvent {
      export type InputTuple = [student: AddressLike, installmentNumber: BigNumberish, amount: BigNumberish, claimDeadline: BigNumberish];
      export type OutputTuple = [student: string, installmentNumber: bigint, amount: bigint, claimDeadline: bigint];
      export interface OutputObject {student: string, installmentNumber: bigint, amount: bigint, claimDeadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ScholarshipApprovedEvent {
      export type InputTuple = [student: AddressLike, totalAmount: BigNumberish, installments: BigNumberish, claimWindowSeconds: BigNumberish];
      export type OutputTuple = [student: string, totalAmount: bigint, installments: bigint, claimWindowSeconds: bigint];
      export interface OutputObject {student: string, totalAmount: bigint, installments: bigint, claimWindowSeconds: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ScholarshipFundedEvent {
      export type InputTuple = [funder: AddressLike, amount: BigNumberish, fundedBalance: BigNumberish];
      export type OutputTuple = [funder: string, amount: bigint, fundedBalance: bigint];
      export interface OutputObject {funder: string, amount: bigint, fundedBalance: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ScholarshipApprovalRelease extends BaseContract {
    
    connect(runner?: ContractRunner | null): ScholarshipApprovalRelease;
    waitForDeployment(): Promise<this>;

    interface: ScholarshipApprovalReleaseInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveScholarship: TypedContractMethod<
      [student: AddressLike, totalAmount: BigNumberish, installments: BigNumberish, claimWindowSeconds: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimInstallment: TypedContractMethod<
      [installmentNumber: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundScholarship: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    fundedBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getApprovedStudents: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getInstallmentInfo: TypedContractMethod<
      [student: AddressLike, installmentNumber: BigNumberish, ],
      [ScholarshipApprovalRelease.InstallmentStructOutput],
      'view'
    >
    

    
    getScholarship: TypedContractMethod<
      [student: AddressLike, ],
      [ScholarshipApprovalRelease.ScholarshipStructOutput],
      'view'
    >
    

    
    isApproved: TypedContractMethod<
      [student: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recoverExpiredInstallment: TypedContractMethod<
      [student: AddressLike, installmentNumber: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    releaseInstallment: TypedContractMethod<
      [student: AddressLike, installmentNumber: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveScholarship'): TypedContractMethod<
      [student: AddressLike, totalAmount: BigNumberish, installments: BigNumberish, claimWindowSeconds: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimInstallment'): TypedContractMethod<
      [installmentNumber: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundScholarship'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'fundedBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getApprovedStudents'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getInstallmentInfo'): TypedContractMethod<
      [student: AddressLike, installmentNumber: BigNumberish, ],
      [ScholarshipApprovalRelease.InstallmentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getScholarship'): TypedContractMethod<
      [student: AddressLike, ],
      [ScholarshipApprovalRelease.ScholarshipStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isApproved'): TypedContractMethod<
      [student: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recoverExpiredInstallment'): TypedContractMethod<
      [student: AddressLike, installmentNumber: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseInstallment'): TypedContractMethod<
      [student: AddressLike, installmentNumber: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ExpiredInstallmentRecovered'): TypedContractEvent<ExpiredInstallmentRecoveredEvent.InputTuple, ExpiredInstallmentRecoveredEvent.OutputTuple, ExpiredInstallmentRecoveredEvent.OutputObject>;
getEvent(key: 'InstallmentClaimed'): TypedContractEvent<InstallmentClaimedEvent.InputTuple, InstallmentClaimedEvent.OutputTuple, InstallmentClaimedEvent.OutputObject>;
getEvent(key: 'InstallmentReleased'): TypedContractEvent<InstallmentReleasedEvent.InputTuple, InstallmentReleasedEvent.OutputTuple, InstallmentReleasedEvent.OutputObject>;
getEvent(key: 'ScholarshipApproved'): TypedContractEvent<ScholarshipApprovedEvent.InputTuple, ScholarshipApprovedEvent.OutputTuple, ScholarshipApprovedEvent.OutputObject>;
getEvent(key: 'ScholarshipFunded'): TypedContractEvent<ScholarshipFundedEvent.InputTuple, ScholarshipFundedEvent.OutputTuple, ScholarshipFundedEvent.OutputObject>;

    filters: {
      
      'ExpiredInstallmentRecovered(address,uint256,uint256)': TypedContractEvent<ExpiredInstallmentRecoveredEvent.InputTuple, ExpiredInstallmentRecoveredEvent.OutputTuple, ExpiredInstallmentRecoveredEvent.OutputObject>;
      ExpiredInstallmentRecovered: TypedContractEvent<ExpiredInstallmentRecoveredEvent.InputTuple, ExpiredInstallmentRecoveredEvent.OutputTuple, ExpiredInstallmentRecoveredEvent.OutputObject>;
    

      'InstallmentClaimed(address,uint256,uint256)': TypedContractEvent<InstallmentClaimedEvent.InputTuple, InstallmentClaimedEvent.OutputTuple, InstallmentClaimedEvent.OutputObject>;
      InstallmentClaimed: TypedContractEvent<InstallmentClaimedEvent.InputTuple, InstallmentClaimedEvent.OutputTuple, InstallmentClaimedEvent.OutputObject>;
    

      'InstallmentReleased(address,uint256,uint256,uint256)': TypedContractEvent<InstallmentReleasedEvent.InputTuple, InstallmentReleasedEvent.OutputTuple, InstallmentReleasedEvent.OutputObject>;
      InstallmentReleased: TypedContractEvent<InstallmentReleasedEvent.InputTuple, InstallmentReleasedEvent.OutputTuple, InstallmentReleasedEvent.OutputObject>;
    

      'ScholarshipApproved(address,uint256,uint256,uint256)': TypedContractEvent<ScholarshipApprovedEvent.InputTuple, ScholarshipApprovedEvent.OutputTuple, ScholarshipApprovedEvent.OutputObject>;
      ScholarshipApproved: TypedContractEvent<ScholarshipApprovedEvent.InputTuple, ScholarshipApprovedEvent.OutputTuple, ScholarshipApprovedEvent.OutputObject>;
    

      'ScholarshipFunded(address,uint256,uint256)': TypedContractEvent<ScholarshipFundedEvent.InputTuple, ScholarshipFundedEvent.OutputTuple, ScholarshipFundedEvent.OutputObject>;
      ScholarshipFunded: TypedContractEvent<ScholarshipFundedEvent.InputTuple, ScholarshipFundedEvent.OutputTuple, ScholarshipFundedEvent.OutputObject>;
    
    };
  }